### ISSUE TITLE
Got "Invalid data: snappy::Uncompress failed" when decompressing raw file

### ISSUE THREAD

**Issue by zxybazh** [kubo/snzip#24]
I compressed a raw file with `snzip -t raw file` and when I run `snzip -t raw -d file.raw` I got the error message of uncompress failed.

**Comment by kubo** [comment]
Could post more information?
* OS version and CPU architecture.
* Test data

It works for me.
```shell
$ ./snzip -t raw INSTALL
$ ./snzip -t raw -d INSTALL.raw 
```
My environment is:
OS: Linux (Ubuntu 16.04 x86_64)
Test data: [INSTALL](https://github.com/kubo/snzip/blob/master/INSTALL)

**Comment by zxybazh** [comment]
Hi, I did the test on Ubuntu 16.04, CPU Intel(R) Core(TM) i7-7700.
Test data is right [here](https://drive.google.com/file/d/108pPgnHytNCvNymhnM2_DZ-w-lDGZakS/view?usp=sharing), part of a TPCH dataset.
Please check, thanks!

**Comment by kubo** [comment]
Thanks. The compressed file is incorrectly compressed because of too big data. The maximum size of raw uncompressed data is 4G according to [this information](https://github.com/google/snappy/blob/1.1.7/format_description.txt#L20).

There are two choices.
1. Make `snzip -t raw` fail when the file size is over 4G.
2. Split file data by 4G and create a compressed file containing concatenated compressed split data.

**Comment by zxybazh** [comment]
Got it, thanks.

**Comment by zxybazh** [comment]
I believe we have to make a new file format to store the file length information for splits of raw compressed data over 4G in case we can split them again when decompressing.

**Comment by kubo** [comment]
What merit does the new file format has? I won't reinvent the wheel unless it has explicit merit.

**Comment by zxybazh** [comment]
Well, you're right. Let's not reinvent the wheel. It's just that I want to make sure that we can get the boundary for every split when we want to decompress the file. If there is something already there, it would be even better. For now, you may just make it fail when file size is over 4G.
